import time
def main():
    print("IQ (Intelligence Quotient) is a measure of a person's reasoning ability and cognitive skills.")
    time.sleep(0.5)
    print("It reflects how well someone can solve problems, understand concepts, learn quickly and apply logic.")
    print()
    time.sleep(0.5)
    print(
        "While it's not a complete measure of intelligence, it gives a useful estimate of someone's mental agility and problem-solving capability.")
    print()
    time.sleep(0.5)
    print("𝗔𝗿𝗲 𝘆𝗼𝘂 𝗿𝗲𝗮𝗱𝘆 𝘁𝗼 𝘁𝗲𝘀𝘁 𝘆𝗼𝘂𝗿 𝗜𝗤?\U0001F600")
    print()
    time.sleep(1)
    input("PRESS ENTER TO START!!")
    print()
    count = 0
    print("Question Number: 1")
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    time.sleep(1)
    print()
    print("A man is looking at a picture. Someone asks him, Whose picture are you looking at?")
    print("He replies:")
    print("Brothers and sisters, I have none.")
    print("But that man's father is my father's son.")
    print()
    print("Who is in the picture?")
    print("a) He himself")
    print("b) His son")
    print("c) His grandson")
    print()
    ans1 = input("𝐖𝐡𝐨 𝐢𝐬 𝐢𝐧 𝐭𝐡𝐞 𝐩𝐢𝐜𝐭𝐮𝐫𝐞? 𝖆/𝖇/𝖈 >>> ")
    if ans1 not in ["a", "b", "c"]:
        print("Please enter a valid input")
        ans1 = input("𝐖𝐡𝐨 𝐢𝐬 𝐢𝐧 𝐭𝐡𝐞 𝐩𝐢𝐜𝐭𝐮𝐫𝐞? 𝖆/𝖇/𝖈 >>> ")
        if ans1 not in ["a", "b", "c"]:
            print("Please enter a valid input")
            ans1 = input("𝐖𝐡𝐨 𝐢𝐬 𝐢𝐧 𝐭𝐡𝐞 𝐩𝐢𝐜𝐭𝐮𝐫𝐞? 𝖆/𝖇/𝖈 >>> ")
    time.sleep(1)
    if ans1 == "b":
        print("You are correct!\U0001F600")
        print()
        print("Answer: His son.")
        print("Explanation: My father's son = me (since there are no siblings).")
        print("So, that man's father is me.")
        print("𝐓𝐡𝐞 𝐦𝐚𝐧 𝐢𝐧 𝐭𝐡𝐞 𝐩𝐢𝐜𝐭𝐮𝐫𝐞 𝐢𝐬 𝐦𝐲 𝐬𝐨𝐧.")
        count = count + 1
    else:
        print("You missed it!\U0001F641")
        print()
        print("Answer: His son.")
        print("Explanation: My father's son = me (since there are no siblings).")
        print("So, that man's father is me.")
        print("𝐓𝐡𝐞 𝐦𝐚𝐧 𝐢𝐧 𝐭𝐡𝐞 𝐩𝐢𝐜𝐭𝐮𝐫𝐞 𝐢𝐬 𝐦𝐲 𝐬𝐨𝐧.")
        count = count
    print()
    time.sleep(1)
    input("PRESS ENTER FOR NEXT QUESTION.")
    print()
    print("Question Number: 2")
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    time.sleep(1)
    print()
    print("Which number should come next in the sequence?")
    print("1, 11, 21, 1211, 111221, ???")
    print()
    print("a) 122211")
    print("b) 212121")
    print("c) 312211")
    print()
    ans2 = input("𝐖𝐡𝐢𝐜𝐡 𝐧𝐮𝐦𝐛𝐞𝐫 𝐬𝐡𝐨𝐮𝐥𝐝 𝐜𝐨𝐦𝐞 𝐧𝐞𝐱𝐭 𝐢𝐧 𝐭𝐡𝐞 𝐬𝐞𝐪𝐮𝐞𝐧𝐜𝐞? 𝖆/𝖇/𝖈 >>>  ")
    if ans2 not in ["a", "b", "c"]:
        print("Please enter a valid input")
        ans2 = input("𝐖𝐡𝐢𝐜𝐡 𝐧𝐮𝐦𝐛𝐞𝐫 𝐬𝐡𝐨𝐮𝐥𝐝 𝐜𝐨𝐦𝐞 𝐧𝐞𝐱𝐭 𝐢𝐧 𝐭𝐡𝐞 𝐬𝐞𝐪𝐮𝐞𝐧𝐜𝐞? 𝖆/𝖇/𝖈 >>>  ")
        if ans2 not in ["a", "b", "c"]:
            print("Please enter a valid input")
            ans2 = input(
                "𝐖𝐡𝐢𝐜𝐡 𝐧𝐮𝐦𝐛𝐞𝐫 𝐬𝐡𝐨𝐮𝐥𝐝 𝐜𝐨𝐦𝐞 𝐧𝐞𝐱𝐭 𝐢𝐧 𝐭𝐡𝐞 𝐬𝐞𝐪𝐮𝐞𝐧𝐜𝐞? 𝖆/𝖇/𝖈 >>>  ")
    print()
    time.sleep(1)
    if ans2 == "c":
        print("You are correct!\U0001F600")
        print()
        print("Answer: c) 312211")
        print("Explanation: This is the look-and-say sequence: ")
        print("- 1 → one 1 → 11")
        print("- 11 → two 1s → 21")
        print("- 21 → one 2, one 1 → 1211")
        print("- 1211 → one 1, one 2, two 1s → 111221")
        print("- 111221 → three 1s, two 2s, one 1 → 312211")
        print("𝐓𝐡𝐞 𝐧𝐞𝐱𝐭 𝐧𝐮𝐦𝐛𝐞𝐫 𝐬𝐡𝐨𝐮𝐥𝐝 𝐛𝐞 𝟑𝟏𝟐𝟐𝟏𝟏")
        count = count + 1
    else:
        print("You missed it!\U0001F641")
        print()
        print("Answer: c) 312211")
        print("Explanation: This is the look-and-say sequence: ")
        print("- 1 → one 1 → 11")
        print("- 11 → two 1s → 21")
        print("- 21 → one 2, one 1 → 1211")
        print("- 1211 → one 1, one 2, two 1s → 111221")
        print("- 111221 → three 1s, two 2s, one 1 → 312211")
        print("𝐓𝐡𝐞 𝐧𝐞𝐱𝐭 𝐧𝐮𝐦𝐛𝐞𝐫 𝐬𝐡𝐨𝐮𝐥𝐝 𝐛𝐞 𝟑𝟏𝟐𝟐𝟏𝟏")
        count = count
    print()
    time.sleep(1)
    input("PRESS ENTER FOR NEXT QUESTION.")
    print()
    print("Question Number: 3")
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    time.sleep(1)
    print()
    print("A doctor gives you 3 pills and tells you to take one every 30 minutes.")
    print("How long will it take to finish them all?")
    print()
    print("a) 1.5 hours")
    print("b) 1 hour")
    print("c) 30 minutes")
    ans3 = input("𝐇𝐨𝐰 𝐥𝐨𝐧𝐠 𝐰𝐢𝐥𝐥 𝐢𝐭 𝐭𝐚𝐤𝐞 𝐭𝐨 𝐟𝐢𝐧𝐢𝐬𝐡 𝐭𝐡𝐞𝐦 𝐚𝐥𝐥? 𝖆/𝖇/𝖈 >>> ")
    if ans3 not in ["a", "b", "c"]:
        print("Please enter a valid input")
        ans3 = input("𝐖𝐡𝐢𝐜𝐡 𝐧𝐮𝐦𝐛𝐞𝐫 𝐬𝐡𝐨𝐮𝐥𝐝 𝐜𝐨𝐦𝐞 𝐧𝐞𝐱𝐭 𝐢𝐧 𝐭𝐡𝐞 𝐬𝐞𝐪𝐮𝐞𝐧𝐜𝐞? 𝖆/𝖇/𝖈 >>>  ")
        if ans3 not in ["a", "b", "c"]:
            print("Please enter a valid input")
            ans3 = input("𝐖𝐡𝐢𝐜𝐡 𝐧𝐮𝐦𝐛𝐞𝐫 𝐬𝐡𝐨𝐮𝐥𝐝 𝐜𝐨𝐦𝐞 𝐧𝐞𝐱𝐭 𝐢𝐧 𝐭𝐡𝐞 𝐬𝐞𝐪𝐮𝐞𝐧𝐜𝐞? 𝖆/𝖇/𝖈 >>>  ")
    print()
    time.sleep(1)
    if ans3 == "b":
        print("You are correct!\U0001F600")
        print()
        print("Answer: b) 1 hour")
        print("Explanation:")
        print("- Take the 1st now")
        print("- 2nd after 30 min")
        print("- 3rd after 60 min")
        count = count + 1
    else:
        print("You missed it!\U0001F641")
        print()
        print("Answer: b) 1 hour")
        print("Explanation:")
        print("- Take the 1st now")
        print("- 2nd after 30 min")
        print("- 3rd after 60 min")
        count = count
    print()
    time.sleep(1)
    input("PRESS ENTER FOR NEXT QUESTION.")
    print()
    print("Question Number: 4")
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    time.sleep(1)
    print()
    print("What comes next in the sequence?")
    print("1, 1, 2, 3, 5, 8, ???")
    print()
    ans4 = input("𝐄𝐧𝐭𝐞𝐫 𝐭𝐡𝐞 𝐀𝐧𝐬𝐰𝐞𝐫: ")
    print()
    time.sleep(1)
    if ans4 == "13":
        print("You are correct!\U0001F600")
        print()
        print("Answer: 13")
        print("Explanation:")
        print("This is Fibonacci sequence, sum of last two numbers.")
        count = count + 1
    else:
        print("You missed it!\U0001F641")
        print()
        print("Answer: 13")
        print("Explanation:")
        print("This is Fibonacci sequence, sum of last two numbers.")
        count = count
    print()
    time.sleep(1)
    input("PRESS ENTER FOR NEXT QUESTION.")
    print()
    print("Question Number: 5")
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    time.sleep(1)
    print()
    print("What comes next in the sequence?")
    print("2, 3, 5, 7, 11, 13, ???")
    print()
    ans5 = input("𝐄𝐧𝐭𝐞𝐫 𝐭𝐡𝐞 𝐀𝐧𝐬𝐰𝐞𝐫: ")
    print()
    time.sleep(1)
    if ans5 == "17":
        print("You are correct!\U0001F600")
        print()
        print("Answer: 17")
        print("Explanation:")
        print("This is sequence of prime numbers.")
        count = count + 1
    else:
        print("You missed it!\U0001F641")
        print()
        print("Answer: 17")
        print("Explanation:")
        print("This is sequence of prime numbers.")
        count = count
    print()
    time.sleep(1)
    input("PRESS ENTER TO GET THE RESULT!!\U0001F603")
    print()
    time.sleep(2)
    print("𝖄𝖔𝖚 𝖌𝖔𝖙 " + 𝖘𝖙𝖗(𝖈𝖔𝖚𝖓𝖙) + " 𝖈𝖔𝖗𝖗𝖊𝖈𝖙 𝖔𝖚𝖙 𝖔𝖋 𝟓.")
    time.sleep(1)
    if count == 5:
        print("𝕰𝖝𝖈𝖊𝖕𝖙𝖎𝖔𝖓𝖆𝖑 𝖗𝖊𝖆𝖘𝖔𝖓𝖎𝖓𝖌 (𝖙𝖔𝖕 𝟓–𝟏𝟎%)\U0001F600")
    if count == 4:
        print("𝕾𝖙𝖗𝖔𝖓𝖌 𝖑𝖔𝖌𝖎𝖈𝖆𝖑 𝖙𝖍𝖎𝖓𝖐𝖎𝖓𝖌 \U0001F600")
    if count == 3:
        print("𝑨𝒗𝒆𝒓𝒂𝒈𝒆 𝑰𝑸 𝒓𝒂𝒏𝒈𝒆")
    if count == 2:
        print("𝐌𝐚𝐲 𝐧𝐞𝐞𝐝 𝐦𝐨𝐫𝐞 𝐭𝐢𝐦𝐞/𝐩𝐫𝐚𝐜𝐭𝐢𝐜𝐞 (𝐨𝐫 𝐧𝐞𝐫𝐯𝐞𝐬 𝐠𝐨𝐭 𝐢𝐧 𝐭𝐡𝐞 𝐰𝐚𝐲!)")
    if count == 1:
        print("𝐌𝐚𝐲 𝐧𝐞𝐞𝐝 𝐦𝐨𝐫𝐞 𝐭𝐢𝐦𝐞/𝐩𝐫𝐚𝐜𝐭𝐢𝐜𝐞 (𝐨𝐫 𝐧𝐞𝐫𝐯𝐞𝐬 𝐠𝐨𝐭 𝐢𝐧 𝐭𝐡𝐞 𝐰𝐚𝐲!)")
    if count == 0:
        print("𝐌𝐚𝐲 𝐧𝐞𝐞𝐝 𝐦𝐨𝐫𝐞 𝐭𝐢𝐦𝐞/𝐩𝐫𝐚𝐜𝐭𝐢𝐜𝐞 (𝐨𝐫 𝐧𝐞𝐫𝐯𝐞𝐬 𝐠𝐨𝐭 𝐢𝐧 𝐭𝐡𝐞 𝐰𝐚𝐲!)")
    print()
    time.sleep(2)
    print("𝐓𝐇𝐀𝐍𝐊 𝐘𝐎𝐔 𝐅𝐎𝐑 𝐏𝐋𝐀𝐘𝐈𝐍𝐆!! \U0001F600")
if __name__ == "__main__":
    main()
